### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Norfaisbest** [sunset-developer/gmad-linux#1]
I get this error when trying to run the program.
Traceback (most recent call last):
  File "gmad.py", line 55, in <module>
    user_input()
  File "gmad.py", line 23, in user_input
    parent_dir = input("Please enter the directory that your addons are located (/home/user/projects/addons): ")
  File "<string>", line 1
    /home/mint/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/addons/
    ^
SyntaxError: invalid syntax

**Comment by na-stewart** [comment]
What version of python are you using?
